name: simplepy
description: |
  An interpreter for a subset of the Python language, written purely in Dart.
  It is intended for adding scripting capabilities to Dart projects and for educational purposes.
version: 1.3.1
repository: https://github.com/thauschildt/simplepy
issue_tracker: https://github.com/thauschildt/simplepy/issues

environment:
  sdk: ^3.7.0

# Add regular dependencies here.
dependencies:
  # path: ^1.8.0

dev_dependencies:
  lints: ^5.0.0
  test: ^1.24.0
