name: simplepy
description: Python subset interpreter written in pure Dart.
version: 0.1.0
repository: https://github.com/thauschildt/simplepy
issue_tracker: https://github.com/thauschildt/simplepy/issues

environment:
  sdk: ^3.7.0

# Add regular dependencies here.
dependencies:
  # path: ^1.8.0

dev_dependencies:
  lints: ^5.0.0
  test: ^1.24.0
